version: '2'
services:
  nginx:
    build: nginx
    links: 
        - flask
    ports: 
        - 8080:8080
  flask:
    build: FeatuReq
    environment:
        - FLASK_APP=run.py
        - APP_SETTINGS=development
        - DATABASE_URL=postgresql://postgres:FeatureReq@postgres/flask_api
        - TEST_DATABASE_URL=postgresql://postgres:FeatureReq@postgres/flask_api_test
    depends_on: 
        - postgres
    links:
        - postgres
    expose:
        - '5000'
    command: /usr/local/bin/gunicorn -w 2 -b :5000 run:app
  postgres:
    environment:
        - POSTGRES_PASSWORD=FeatureReq
        - POSTGRES_DB=flask_api
    expose: 
        - '5432'
    image: postgres
